### PR TITLE
Fix: Removing weighted distribution from Numeric Generators

### LINKED ISSUE #6: Double generator produces the values that repeat too often
I noticed that Generate.double.value is producing values that repeat pretty often. This results in a lot of flaky tests. I also have a feeling there is the same problem with Ints and strings. We fetch by random value and get the data unexpectedly (not so random after all). Take a look at distribution:

0.0
10654.40514007162
-25000.0
9809.305301695917
-17137.603961595465
-13373.27128064092
-17173.188179482015
16215.946247337735
25000.0
-1.0
2589.5009772317026
2989.3820258243213
-1.0
1.0
14621.637434678836
6639.72649885136
4480.467924157816
15071.979639947393
-7803.325196510235
0.0
-13639.018501387918
-1.0
0.0
-1.0
25000.0
0.0
-680.0489962394313
25000.0
0.0
5603.971067112001
1.0
25000.0
-3492.0292956218727
1914.9050728849652
1.0
22126.890952288304
1.0
6454.447629369719
15965.27860647165
6313.167878111624
18430.9741005084
-22972.349963552137
-11222.655123316128
-25000.0
8014.81489075796
2307.609420652556
-25000.0
18074.95636105605
-7175.513714450248
0.0
1218.9087878974278
-25000.0
0.0
16849.186106839807
-7690.1377231373845
-7782.421061686346
0.0
-3344.0802255245944
1.0
0.0
-25000.0
4893.948251260506
8270.36394507093
-25000.0
25000.0
-7114.822557374027
4289.880108282228
0.0
2206.825253589799
0.0
1.0
1.0
-24578.837875688303
1.0
6921.482685096758
24474.803752991596
-20810.114858273846
25000.0
-20079.297251322576
12549.678213572632
21720.167108810077
1.0
-1.0
-12238.999581847349
-17554.682615207123
24373.376291099776
-25000.0
21716.763270486073
13288.834895604676
0.0
-15452.159393295105
-25000.0
-25000.0
1.0
1.0
7592.477246329603
-12954.522292076497
-8686.495748247775
-1.0
-17837.222289273202
25000.0
25000.0
-25000.0
-13569.92578868068
-1.0

### PR DESCRIPTION
**Pull request by fulrich**
Fixes: https://github.com/fulrich/test-charged/issues/6

As reported in the issue above the numeric generators were using `chooseNum` which caused extremities and 0/1 to be weighted stronger. This is very useful for targeted testing but TestCharged is more focused on data generation at a larger scale.

This PR creates a test that checks that we don't have over 5% of our generated values being an extremity. It then updates our `NumericGenerators` to use `choose` instead of `chooseNum`

### CODE REVIEW

**Comment by fulrich** [comment]
New distribution from the `Generate.double.default` for 50 values:

```
-10652.913139341146
-14064.816939042346
5834.861883496
-24507.41450340026
13007.555408990658
-21411.555687867774
-11180.320184945047
19267.67778634155
-16710.13047086672
-4357.237764224941
-23137.0743713878
-14206.168375368394
5594.407028019781
-11180.53083326041
16620.890862695873
-15470.913629881177
-12386.704747433052
-9653.814969571018
20449.205427399203
-345.84364374967845
22479.17208169907
15341.756030576034
3654.5401216237733
12930.043435323583
-17766.272580699493
1706.7584138021048
11642.374567693943
-10959.725813562593
-11190.155001741137
17864.090238656747
-23597.94839309423
19247.26746832305
-22913.39133569834
-20161.454905132025
-19468.246602112955
7298.987768486128
-9469.470376815354
14691.528722647257
-17107.92837338772
7858.304607955804
-22348.353353413746
13947.079632041241
-21673.86358427792
-24144.946913517324
-9995.018924145916
19430.073769665214
-23466.58854664965
-23479.38669697277
-837.5875424657352
18618.633453028924
```

**Review by vmandrychenko — APPROVED** [review]

File: src/test/scala/com/github/fulrich/testcharged/generators/numerics/NumericGeneratorDistributionUTest.scala [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+  test("The float generator does not weight extremities") {
+    ensureExtremitiesNotWeighted(FloatGenerators)
+  }
+
+  test("The short generator does not weight extremities") {
+    ensureExtremitiesNotWeighted(ShortGenerators)
+  }
+
+  def ensureExtremitiesNotWeighted[A : Choose](generator: NumericGenerator[A])(implicit numeric: Numeric[A]): Unit = {
```
Comment (vmandrychenko) [inline src/test/scala/com/github/fulrich/testcharged/generators/numerics/NumericGeneratorDistributionUTest.scala:31]: 👍

**Review by vmandrychenko — APPROVED** [review]
